#!/usr/bin/bash

# ---------------------------------- Symlinks ----------------------------------

# get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# make sure the directory exists
mkdir -p ~/.config/rofi

# create symlinks
ln -sf $DIR/config.rasi ~/.config/rofi/config.rasi
ln -sf $DIR/nord.rasi ~/.config/rofi/nord.rasi
