#!/usr/bin/bash

# ---------------------------------- Symlinks ----------------------------------

# get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# make sure the directory exists
mkdir -p ~/.config/i3status

# create symlinks
ln -sf $DIR/config ~/.config/i3status/config
ln -sf $DIR/wrapper.py ~/.config/i3status/wrapper.py
