#!/usr/bin/bash

# ---------------------------------- Symlinks ----------------------------------

# get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# make sure the directory exists
mkdir -p ~/.config/nvim

# create symlinks
# link everything in the directory to the .config/nvim
# except for setup
for file in $DIR/*; do
    if [ "$file" != "$DIR/setup" ]; then
        ln -sf $file ~/.config/nvim
    fi
done

