#!/usr/bin/bash

# get script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# ---------------------------------- Symlinks ----------------------------------

# .gitignore
ln -sf "$DIR/.gitignore" "$HOME/.gitignore"
ln -sf "$DIR/.gitconfig" "$HOME/.gitconfig"

# .bashrc
ln -sf "$DIR/.bashrc" "$HOME/.bashrc"



