#!/usr/bin/bash
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# make a env file in /opt/monkey/services/env
sudo mkdir -p /opt/monkey/services
sudo chown -R monkey /opt/monkey/
echo "HOME=$HOME" > /opt/monkey/services/env

loginctl enable-linger $USER
mkdir -p ~/.config/systemd/user

# copy all service and timer files to ~/.config/systemd/user
files = $(find $SCRIPTPATH -type f -name "*.service" -o -name "*.timer")
echo $files
for file in $files; do
    echo "Copying $file to ~/.config/systemd/user"
    cat $file | envsubst > ~/.config/systemd/user/$(basename $file)
done

# enable the specific services
services=(
    $SCRIPTPATH/cronwhip.timer
    $SCRIPTPATH/watch-dot.service
    $SCRIPTPATH/watch-jupyter-backup.service
    $SCRIPTPATH/watch-monkey.service
    $SCRIPTPATH/watch-site.service
)

# for each file in the directory that ends with .service
# replace the env variables and write to ~/.config/systemd/user
for service in $services; do
    echo "enableing $service"
    # enable the servces
    systemctl --user enable $(basename $service)
    systemctl --user start $(basename $service)
done

