#!/usr/bin/bash
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# make a env file in /opt/monkey/services/env
sudo mkdir -p /opt/monkey/services
sudo chown -R monkey /opt/monkey/
echo "HOME=$HOME" > /opt/monkey/services/env

loginctl enable-linger $USER
mkdir -p ~/.config/systemd/user

# for each file in the directory that ends with .service or .timer
units=$(find $SCRIPTPATH -type f \( -name "*.service" -o -name "*.timer" \))
# replace the env variables and write to ~/.config/systemd/user
for unit in $units; do
    echo "Copying $unit to ~/.config/systemd/user"
    cat $unit | envsubst > ~/.config/systemd/user/$(basename $unit)
    echo "enabling $unit"
    # enable the units
    systemctl --user enable $(basename $unit)
    # only start services, not timers (timers start automatically when enabled)
    if [[ $unit == *.service ]]; then
        systemctl --user start $(basename $unit)
    fi
done

