#!/usr/bin/bash

# ---------------------------------- Symlinks ----------------------------------

# get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# make sure the directory exists
mkdir -p ~/.config/kitty

# create symlinks
ln -sf $DIR/kitty.conf ~/.config/kitty/kitty.conf
ln -sf $DIR/nord.conf ~/.config/kitty/nord.conf
