#!/usr/bin/bash
# this script checksout to a branch

# get all of the avalible git branches including remote branches
# remove the first two characters of each line
branches=$(git branch -al | cut -c 3-)
# --------------------------------- completion ---------------------------------
if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    # echo valid completions after this point
    echo $branches | grep "$prefix"
    exit
fi
