#!/usr/bin/bash
# this script checksout to a branch

# get all of the avalible git branches including remote branches
# remove the first two characters of each line
branches=$(git branch -al | cut -c 3-)
# --------------------------------- completion ---------------------------------
if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    # echo valid completions after this point
    # split branches by newlines
    echo "$branches" | grep "$prefix"
    exit
fi

# --------------------------------- main ---------------------------------
b=$1
if [[ -z $b ]]; then
    echo "usage: branch <branch>"
    exit
fi

# if the branch exists checkout to it
if [[ $(echo "$branches" | grep "$b") ]]; then
    git checkout $b
    exit
fi

# if the branch does not exist checkout with -b
git checkout -b $b


