#!/usr/bin/bash
# ---------------------------------- the code ----------------------------------
today() {
    find "$SNIPPETS" -maxdepth 2 -mindepth 2 -not -path "*/.*" \
    | rev | cut -d '/' -f 1-2 | rev 
}

usage() {
    echo "Usage: cal [today|list]"
}

# --------------------------------- completion ---------------------------------
opts="today usage"
if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
   echo $(compgen -W "$opts" -- "$prefix")
    exit
fi

case "$1" in
    today) today ;;
    usage) usage ;;
    *) today ;;
esac
