#!/usr/bin/bash

# claude-pipe is a simple script to operate on the stdin input and stdout output
# its used as so
# echo "input" | claude-pipe prompt you want to feed claude > output.txt

input=$(cat)
prompt="$*"

echo "$prompt

Input to process:
$input" | claude -p
