#!/usr/bin/bash
# Cronwrapper is a helper script to run cron commands with specific user and env vars
# Usage: cron-wrapper <command> 

# read certain env var lines from .bashrc and export them here
export HOME="/home/monkey"

# run any line with "export" in it from .bashrc
while IFS= read -r line; do
    if [[ $line == export* ]]; then
        echo "Exporting: $line"
        eval "$line"
    fi
done < /home/monkey/.bashrc


"$@"

