#!/usr/bin/bash
# Cronwrapper is a helper script to run cron commands with specific user and env vars
# Usage: cron-wrapper <command> 

# read certain env var lines from .bashrc and export them here

export HOME="/home/monkey"
export $(grep -E '^(PATH|ATP_DIR|TODO_DIR|REPOS)=' ~/.bashrc | sed 's/^/export /')

"$@"

