#!/bin/sh
# shell script to prepend i3status with more stuff

i3status | while :
do
        read line
        echo "kubectx: $(kubectx -c) | kubens: $(kubens -c) | dockerctx: $(docker context show) | $line" || exit 1
done

