#!/usr/bin/bash

# --------------------------------- completion ---------------------------------

options=(
    hours
    minutes
    date
    seconds
    ns
)

if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    for option in "${options[@]}"; do
        if [[ $option == $prefix* ]]; then
            echo "$option"
        fi
    done
    exit
fi

mode=${1:-second}

date -I$mode

