#!/usr/bin/bash

# read flags
# check if --process-sim is set
process_sim=false
for arg in "$@"; do
    if [ "$arg" == "--process-sim" ]; then
        process_sim=true
        break
    fi
done

num_file=/tmp/ito_num
# read the number from the file, if the file does not exist, set it to 0
if [ -f $num_file ]; then
  num=$(cat $num_file)
else
  num=0
fi

# write incremented number back to the file
echo $((num + 1)) > $num_file

# create the tag 0.0.0-ag-ito-$num
tag=0.0.0-ag-ito-$num

# print the tag
echo "Building image with tag: $tag"

# build the image
pattern_remote_build -t $tag

# uninstall old images if present
if [ "$process_sim" = true ]; then
  helm uninstall process-sim
else
  helm uninstall robot-control

# deploy new code
# if process-sim is set deploy the process-sim chart 
if [ "$process_sim" = true ]; then
  pattern molecule deploy process-sim -t $tag -- --values charts/process-sim/egll-dhl-values.yaml --set config_tag=$tag
else
    pattern molecule deploy robot-control -t $tag -- --values charts/robot-control/test-ito-process-path.yaml
fi

