#!/usr/bin/bash
if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    # echo valid completions after this point
    find  -maxdepth 1 -type f -name "*.excalidraw" -printf "%f" | grep "$prefix"
    exit
fi


# -------------------------------- the command --------------------------------
# yoink this from .local/share/applications/chrome-blaskhajdhfaksdfsa.desktop
/opt/google/chrome/google-chrome --profile-directory=Default --app-id=kmcnjdcipmgchfndpapkoecbidofdpbc $@ & 
