#!/usr/bin/bash
dirs=( . $PATTERN_PLANNING_DIR)

if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    # echo valid completions after this point
    # iterate through dirs and search
    for 
       # find *.excalidraw -maxdepth 1 -type f -printf "%f" | grep "$prefix"

    exit
fi


# -------------------------------- the command --------------------------------
# yoink this from .local/share/applications/chrome-blaskhajdhfaksdfsa.desktop
/opt/google/chrome/google-chrome --profile-directory=Default --app-id=kmcnjdcipmgchfndpapkoecbidofdpbc $@ & 
