#!/usr/bin/bash
# ---------------------------------- the code ----------------------------------

check_khal() {
    if ! command -v khal &> /dev/null; then
        echo "khal not found"
        exit
    fi
}


today() {
    check_khal
    khal list --format '{cyan-bold}{start-end-time-style} {calendar-color}{title}{repeat-symbol}' --day-format '{yellow}{name}, {date}' --exclude-calendar 'Pattern Updates' --exclude-calendar 'Sneha'
}

usage() {
    echo "Usage: cal [today|list]"
}

# --------------------------------- completion ---------------------------------
opts="today usage"
if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    results=$(compgen -W "$opts" -- "$prefix")
    for i in $results; do
        echo "$i"
    done
    exit
fi

case "$1" in
    today) today ;;
    usage) usage ;;
    *) today ;;
esac
