#!/usr/bin/bash

# newx - create a new script in the $SCRIPTS directory also
# dumps whatever is the newx snippet into the new script

test ! -n "${SCRIPTS}"  && echo "SCRIPTS not set" && exit 1;
test ! -n "${1}"  && echo "usage: newscript <name>" && exit 1;

path="${SCRIPTS}/${1}"

if test -e "${path}"; then
  read -p "${1} already exists. Edit? " yes
  case "${yes}" in
    y|yes|yep|yeppers|yeah|ok|okay) exec nvim "${path}"
  esac
  exit 0
fi

snip newx > "${path}"
chmod +x "${path}" 
exec nvim +2 "${path}"
