#!/usr/bin/bash
# ---------------------------------- the code ----------------------------------
[[ -z $SITEREPO ]] && echo "SITEREPO directory undefined" && exit 1
BLOGPOSTS="$SITEREPO/content/projects"

list() {
    find "$BLOGPOSTS" -maxdepth 2 -mindepth 2 -not -path "*/.*" \
    | rev | cut -d '/' -f 1-2 | rev 
}

usage() {
    echo "Usage: post list|usage|<snippet-name>"
}

post() {
    # check we got an argument
    [[ -z $1 ]] && usage && exit 1

    local p="$BLOGPOSTS/$1"

    cd "$SITEREPO"
    # launch hugo server
    hugo server -D  &> /dev/null &
    
    # open the post in the browser
    # strip the .md extension
    local url="http://localhost:1313/$(echo "$1" | rev | cut -d '.' -f 2- | rev)"
    xdg-open "$url" &> /dev/null  &

    # kill hugo server when we exit
    trap "killall background" EXIT
    # open the post in the editor
    $EDITOR "$p"
}

# --------------------------------- completion ---------------------------------


if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    list | grep "$prefix" 
    exit
fi

case "$1" in
    list) list ;;
    usage) usage ;;
    *) post "$1" ;;
esac

