#!/usr/bin/bash
# --------------------------------- completion ---------------------------------
if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    # echo valid completion after this

    exit
fi

# ---------------------------------- command ----------------------------------
while true
do
clear
echo "Command: $@" '| Press Ctrl+C to exit'
$($@)
sleep 1
done

