#!/usr/bin/bash

# check if $1 was supplied and is a dir
# if not use current dir
searchDir=${1:-.}

cd $searchDir

rg --color=always --line-number --no-heading --smart-case "${*:-}" | \
fzf --ansi \
    --color hl:-1:underline,hl+:-1:underline:reverse \
    --delimiter : \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'right,50%' \
    --bind 'enter:become(vim {1} +{2})' \

