#!/usr/bin/bash
# ---------------------------------- the code ----------------------------------
[[ -z $SITE ]] && echo "SITE directory undefined" && exit 1

list() {
    find "$SNIPPETS" -maxdepth 2 -mindepth 2 -not -path "*/.*" \
    | rev | cut -d '/' -f 1-2 | rev 
}

usage() {
    echo "Usage: site list|usage|<snippet-name>"
}

site() {
    # check we got an argument
    [[ -z $1 ]] && usage && exit 1


    local post="$SITE/$1"
    # find the post we want and check its readable
    # check that we dont have more than 1 file 
    [[ ! -e $post ]] && echo "Snippet $post not found" && exit 1

    # open the post in the editor
    $EDITOR "$post"
}

# --------------------------------- completion ---------------------------------


if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    list | grep "$prefix" 
    exit
fi

case "$1" in
    list) list ;;
    usage) usage ;;
    *) site "$1" ;;
esac

