#!/usr/bin/bash
# ---------------------------------- the code ----------------------------------
[[ -z $SNIPPETS ]] && echo "SNIPPETS directory undefined" && exit 1k

list() {
      find "$SNIPPETS" -type f -not -path "*/.*"  -exec basename {} \;
}

usage() {
    echo "Usage: snip list|usage|<snippet-name>"
}

snip() {
    local snippet="$1"
    # check we got an argument
    [[ -z $snippet ]] && usage && exit 1

    # find the snippet we want and check its readable
    local snippet_file=$(find "$SNIPPETS" -type f -name "$snippet" -not -path "*/.*")
    # check that we dont have more than 1 file 
    [[ $(echo "$snippet_file" | wc -l) -gt 1 ]] && echo "More than one snippet found" && exit 1
    [[ ! -r $snippet_file ]] && echo "Snippet $snippet not found" && exit 1
   
    # print the snippet
    cat "$snippet_file"
}

# --------------------------------- completion ---------------------------------


if [[ -n $COMP_LINE ]]; then
    prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
    list | grep "^$prefix" 
    exit
fi

case "$1" in
    list) list ;;
    usage) usage ;;
    *) snip "$1" ;;
esac
